id: P004450
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ5669
  title: འཇིགས་བྱེད་ལྷ་བཅུ་གསུམ་གྱི་བསྐྱེད་རྫོགས་ཁྲིད་ཡིག
  author: ''
  volumes:
    c83d368849ef4fc5bab1e20a1e3c1e36:
      image_group_id: I1KG10573
      title: ''
      volume_number: 1
      total_pages: 370
      base_file: v001.txt
